--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/21/2023 17:05:10
-- Server version: 10.4.19
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE uas;

--
-- Drop table `product`
--
DROP TABLE IF EXISTS product;

--
-- Set default database
--
USE uas;

--
-- Create table `product`
--
CREATE TABLE product (
  id int(11) NOT NULL AUTO_INCREMENT,
  nama varchar(255) DEFAULT NULL,
  bahan varchar(255) DEFAULT NULL,
  harga_beli int(11) DEFAULT NULL,
  keterangan_harga_beli varchar(255) DEFAULT NULL,
  harga_jual int(11) DEFAULT NULL,
  keterangan_harga_jual varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table product
--
INSERT INTO product VALUES
(1, '0.6140109588715917', '0.6891051598838877', 0, 'Keterangan Beli 0.20795981480772885', 0, 'Keterangan Beli 0.39066759078712543'),
(4, '7.480377583626296E-4', '0.8237106930901251', 0, 'Keterangan Beli 0.6432211291999816', 12000, 'Keterangan Beli 0.4204973217408793'),
(7, '0.6329139062472166', '0.19205064324359722', 0, 'Keterangan Beli 0.12843881694776849', 0, 'Keterangan Beli 0.8146271662298782'),
(8, '0.5486779143855297', '0.23639695187683485', 0, 'Keterangan Beli 0.6531315332426282', 0, 'Keterangan Beli 0.18059301240087677');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;