
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nhari
 */
public class Cabang extends javax.swing.JFrame {

    /**
     * Creates new form Karyawan
     */
    public Cabang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblCabang = new javax.swing.JTable();
        jTxtNama = new javax.swing.JTextField();
        jBtnSimpan = new javax.swing.JButton();
        jTxtId = new javax.swing.JTextField();
        jBtnDelete = new javax.swing.JButton();
        jTxtKode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtLokasi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nama");

        jTblCabang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Kode", "Nama", "Lokasi", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblCabang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblCabangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblCabang);
        if (jTblCabang.getColumnModel().getColumnCount() > 0) {
            jTblCabang.getColumnModel().getColumn(0).setResizable(false);
            jTblCabang.getColumnModel().getColumn(1).setResizable(false);
            jTblCabang.getColumnModel().getColumn(2).setResizable(false);
            jTblCabang.getColumnModel().getColumn(3).setResizable(false);
        }

        jTxtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNamaActionPerformed(evt);
            }
        });

        jBtnSimpan.setText("Simpan");
        jBtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSimpanActionPerformed(evt);
            }
        });

        jTxtId.setText("-1");

        jBtnDelete.setText("Delete");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jTxtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKodeActionPerformed(evt);
            }
        });

        jLabel2.setText("Kode");

        jLabel3.setText("Lokasi");

        jTxtLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtLokasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnDelete)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtNama)
                            .addComponent(jTxtKode)
                            .addComponent(jTxtLokasi))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSimpan)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNamaActionPerformed

    private void jBtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            DatabaseConnection conn = new DatabaseConnection();
            String nama = jTxtNama.getText();
            String kode = jTxtKode.getText();
            String lokasi = jTxtLokasi.getText();
            int id = Integer.parseInt(jTxtId.getText());
            if(id == -1){
                String sql = "INSERT INTO cabang (kode, lokasi, nama) VALUES ('"+kode+"', '"+lokasi+"', '"+nama+"');";
                conn.cn.execute(sql);
            }else{
                String sql = "UPDATE cabang c SET kode = '"+kode+"', lokasi = '"+lokasi+"', nama = '"+nama+"' WHERE id = "+id+";";
                conn.cn.execute(sql);
            }
            this.getList();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jBtnSimpanActionPerformed
    private void resetForm(){
        jBtnSimpan.setText("Simpan");
        jTxtNama.setText("");
        jTxtId.setText("-1");
        jTxtId.hide();
    }
    private void getList(){
        try {
            this.resetForm();
            DatabaseConnection conn = new DatabaseConnection();
            String sql = "SELECT * FROM cabang p;";
            ResultSet rs = conn.cn.executeQuery(sql);
            
            DefaultTableModel tm = (DefaultTableModel)jTblCabang.getModel();
            tm.setRowCount(0);
            int i = 1;
            while(rs.next()){
                Object o[] = {i,rs.getString("kode"),rs.getString("nama"),rs.getString("lokasi"),rs.getInt("id")};
                tm.addRow(o);
                i = i + 1;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println(e.getMessage());
        }
    }
    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        try {
            DatabaseConnection conn = new DatabaseConnection();
            int input = JOptionPane.showConfirmDialog(null, "Apakah anda yakin menghapus "+jTxtNama.getText()+" ?","Pilih salah satu",JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            if(input == 0){
                String sql = "DELETE FROM cabang WHERE id = "+jTxtId.getText()+";";
                conn.cn.execute(sql);                                
                this.getList();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println(e.getMessage());
        }	
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getList();
    }//GEN-LAST:event_formWindowOpened

    private void jTblCabangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblCabangMouseClicked
        try {
            JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            String Kode=source.getModel().getValueAt(row, 1)+"";
            String nama=source.getModel().getValueAt(row, 2)+"";
            String lokasi=source.getModel().getValueAt(row, 3)+"";
            String id=source.getModel().getValueAt(row, 4)+"";
            jTxtId.setText(id);
            jTxtNama.setText(nama);
            jTxtKode.setText(Kode);
            jTxtLokasi.setText(lokasi);
            jBtnSimpan.setText("Rubah");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jTblCabangMouseClicked

    private void jTxtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKodeActionPerformed

    private void jTxtLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtLokasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblCabang;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtKode;
    private javax.swing.JTextField jTxtLokasi;
    private javax.swing.JTextField jTxtNama;
    // End of variables declaration//GEN-END:variables
}
