
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nhari
 */
public class Karyawan extends javax.swing.JFrame {

    /**
     * Creates new form Karyawan
     */
    public Karyawan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblKaryawan = new javax.swing.JTable();
        jTxtNamaKaryawan = new javax.swing.JTextField();
        jBtnSimpanKaryawan = new javax.swing.JButton();
        jTxtIdKaryawan = new javax.swing.JTextField();
        jBtnDeleteKaryawan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nama");

        jTblKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Kode Karyawan", "Nama"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblKaryawan);
        if (jTblKaryawan.getColumnModel().getColumnCount() > 0) {
            jTblKaryawan.getColumnModel().getColumn(0).setResizable(false);
            jTblKaryawan.getColumnModel().getColumn(1).setResizable(false);
            jTblKaryawan.getColumnModel().getColumn(2).setResizable(false);
        }

        jTxtNamaKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNamaKaryawanActionPerformed(evt);
            }
        });

        jBtnSimpanKaryawan.setText("Simpan");
        jBtnSimpanKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSimpanKaryawanActionPerformed(evt);
            }
        });

        jTxtIdKaryawan.setText("-1");

        jBtnDeleteKaryawan.setText("Delete");
        jBtnDeleteKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteKaryawanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTxtIdKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnSimpanKaryawan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnDeleteKaryawan)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtNamaKaryawan))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSimpanKaryawan)
                    .addComponent(jTxtIdKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDeleteKaryawan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNamaKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNamaKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNamaKaryawanActionPerformed

    private void jBtnSimpanKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSimpanKaryawanActionPerformed
        // TODO add your handling code here:
        try {
            DatabaseConnection conn = new DatabaseConnection();
            String nama = jTxtNamaKaryawan.getText();
            int id = Integer.parseInt(jTxtIdKaryawan.getText());

            if(nama == "" ){
                throw new Exception("Ada Field kosong");
            }
            if(id == -1){
                
                String sql = "INSERT INTO karyawan (nama)  VALUES ('"+nama+"');";
                conn.cn.execute(sql);
            }else{
                String sql = "UPDATE karyawan SET nama = '"+nama+"' WHERE id = "+id+";";
                conn.cn.execute(sql);
            }
            this.getListKaryawan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jBtnSimpanKaryawanActionPerformed
    private void resetForm(){
        jBtnSimpanKaryawan.setText("Simpan");
        jTxtNamaKaryawan.setText("");
        jTxtIdKaryawan.setText("-1");
        jTxtIdKaryawan.hide();
    }
    private void getListKaryawan(){
        try {
            this.resetForm();
            DatabaseConnection conn = new DatabaseConnection();
            String sql = "SELECT * FROM karyawan p;";
            ResultSet rs = conn.cn.executeQuery(sql);
            
            DefaultTableModel tm = (DefaultTableModel)jTblKaryawan.getModel();
            tm.setRowCount(0);
            int i = 1;
            while(rs.next()){
                Object o[] = {i,rs.getInt("id"),rs.getString("nama")};
                tm.addRow(o);
                i = i + 1;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println(e.getMessage());
        }
    }
    private void jBtnDeleteKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteKaryawanActionPerformed
        try {
            DatabaseConnection conn = new DatabaseConnection();
            int input = JOptionPane.showConfirmDialog(null, "Apakah anda yakin menghapus "+jTxtNamaKaryawan.getText()+" ?","Pilih salah satu",JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            if(input == 0){
                String sql = "DELETE FROM karyawan WHERE id = "+jTxtIdKaryawan.getText()+";";
                conn.cn.execute(sql);                                
                this.getListKaryawan();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println(e.getMessage());
        }	
    }//GEN-LAST:event_jBtnDeleteKaryawanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getListKaryawan();
    }//GEN-LAST:event_formWindowOpened

    private void jTblKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblKaryawanMouseClicked
        try {
            JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            String id=source.getModel().getValueAt(row, 1)+"";
            String nama=source.getModel().getValueAt(row, 2)+"";
            jTxtIdKaryawan.setText(id);
            jTxtNamaKaryawan.setText(nama);
            jBtnSimpanKaryawan.setText("Rubah");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jTblKaryawanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDeleteKaryawan;
    private javax.swing.JButton jBtnSimpanKaryawan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblKaryawan;
    private javax.swing.JTextField jTxtIdKaryawan;
    private javax.swing.JTextField jTxtNamaKaryawan;
    // End of variables declaration//GEN-END:variables
}
